### ISSUE TITLE
Can't Record Video in Instagram 

### ISSUE THREAD

**Issue by alfadly** [Moyster/mm_device_meizu_m2note#1]
Hi, I've done records logcat but i confused for take detailed log: / so i upload log at http://upfile.mobi/9jWo851InSi maybe will help for fix bug. Thank you

**Comment by Moyster** [comment]
all good ?

**Comment by alfadly** [comment]
yup, but need force close app instagram, facebook etc. for run video
recording. Build 2 i trouble connect bluetooth YET M1 but in build 1 is fine

2017-01-04 20:07 GMT+07:00 Moyster <notifications@github.com>:
