### ISSUE TITLE
Notification Not working in latest build

### ISSUE THREAD

**Issue by tasteris** [Moyster/mm_device_meizu_m2note#8]
Moyster Hi,

In the latest build notifications from yahoo mail, gmail are not working properly while they do on the build of 01/01. The problem is that if for example the phone is awake and an email arrives the application won't notify you, you have to open the application in order to see that a new email arrived.

I performed a clean wipe twice on the latest build and verified that indeed this is the case, i just reverted to previous build and this works fine. I don't know what kind of logs i can provide, please let me know.

Thanks for your great work as always.

**Comment by Moyster** [comment]
Hi there,
It's not a bug, Marshmallow has battery economy features, you have to allow Gmail and any other app to run without battery optimisations.  
Settings > Battery > ... > Battery Optimisation  
And allow every app you want to run in the background (for notifications / push updates, etc)

**Comment by tasteris** [comment]
Hi Moyster,

I am aware of that and already tried it. Still the same. Currently on 01/01 build with yahoo and gmail baterry optimized and notifications working fine

Thanks
